apiVersion: compute-node.openstack.org/v1alpha1
kind: ComputeNodeOpenStack
metadata:
  name: example-computenodeopenstack
  namespace: openshift-machine-api
spec:
  # Add fields here
  roleName: worker-osp
  clusterName: ostest
  baseWorkerMachineSetName: ostest-worker-0
  k8sServiceIp: 172.30.0.1
  apiIntIp: 192.168.111.5
  workers: 0
  corePinning: "4-7"
  infraDaemonSets:
  - name: multus
    namespace: openshift-multus
  - name: node-exporter
    namespace: openshift-monitoring
  - name: machine-config-daemon
    namespace: openshift-machine-config-operator
