
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: computenodeopenstacks.compute-node.openstack.org
spec:
  group: compute-node.openstack.org
  names:
    kind: ComputeNodeOpenStack
    listKind: ComputeNodeOpenStackList
    plural: computenodeopenstacks
    singular: computenodeopenstack
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ComputeNodeOpenStack is the Schema for the computenodeopenstacks
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ComputeNodeOpenStackSpec defines the desired state of ComputeNodeOpenStack
          properties:
            baseWorkerMachineSetName:
              description: Base Worker MachineSet Name
              type: string
            cell:
              description: Cell the computes are assigned to, default cell1
              type: string
            clusterName:
              description: Cluster name
              type: string
            compute:
              description: Compute/Nova configuration
              properties:
                neutronSecrets:
                  description: Neutron secret containing the needed password, default
                    "neutron-secret"
                  type: string
                novaComputeCPUDedicatedSet:
                  description: CPU Dedicated Set (pinning)
                  type: string
                novaComputeCPUSharedSet:
                  description: CPU Shared Set
                  type: string
                novaSecrets:
                  description: Nova secret containing the needed password, default
                    "nova-secret"
                  type: string
                placementSecrets:
                  description: Placement secret containing the needed password, default
                    "placement-secret"
                  type: string
                sshdPort:
                  description: sshd migration port
                  format: int32
                  type: integer
                transportURLSecret:
                  description: TransportURL secret containing the needed password,
                    default nova-<CELL>-transport-url
                  type: string
              type: object
            corePinning:
              description: Cores Pinning
              type: string
            dedicated:
              description: Make or not the Node dedicated to OSP workloads (does not
                account for infra pods)
              type: boolean
            drain:
              description: Node draining configuration options
              properties:
                drainPodImage:
                  description: Image used for drain pod which performs compute removal,
                    this is usually an image which has the openstackclient and osc-placement
                    packages installed.
                  type: string
                enabled:
                  description: 'Automatic draining (live migrate off instances) of
                    the node, global switch, which can be overwritten on per Node
                    base using NodeToDelete struct. Default: false'
                  type: boolean
              required:
              - drainPodImage
              type: object
            infraDaemonSets:
              description: Infra DaemonSets needed
              items:
                description: InfraDaemonSet defines the daemon set required
                properties:
                  name:
                    description: Name
                    type: string
                  namespace:
                    description: Namespace
                    type: string
                required:
                - name
                - namespace
                type: object
              type: array
            network:
              description: Network/Neutron configuration
              properties:
                bridgeMappings:
                  type: string
                mechanismDrivers:
                  type: string
                nic:
                  type: string
                servicePlugins:
                  type: string
                sriov:
                  items:
                    description: SriovConfig defines SRIOV config parameters, such
                      as nic information.
                    properties:
                      deviceType:
                        type: string
                      interface:
                        type: string
                      mtu:
                        format: int32
                        type: integer
                      network:
                        type: string
                      numVfs:
                        format: int32
                        type: integer
                    required:
                    - deviceType
                    - interface
                    - network
                    type: object
                  type: array
              required:
              - nic
              type: object
            networkGateway:
              description: Make the nodes to be Network Gateways
              type: boolean
            nodesToDelete:
              description: Nodes to delete upon scale down
              items:
                description: NodeToDelete defines the name of the node to delete and
                  if automatic drain is needed
                properties:
                  drain:
                    description: Automatic draining of the node
                    type: boolean
                  name:
                    description: Node Name
                    type: string
                required:
                - name
                type: object
              type: array
            openStackClientAdminSecret:
              description: user secrets used to connect to OpenStack API via openstackclient
              type: string
            openStackClientConfigMap:
              description: openstackclient configmap which holds information to connect
                to OpenStack API
              type: string
            roleName:
              description: Name of the worker role created for OSP computes
              type: string
            selinuxDisabled:
              description: Manage selinux - Defaults to false
              type: boolean
            serviceAccount:
              description: service account used to create pods
              type: string
            workers:
              description: Number of workers
              format: int32
              type: integer
          required:
          - baseWorkerMachineSetName
          - clusterName
          - drain
          - openStackClientAdminSecret
          - openStackClientConfigMap
          - roleName
          - serviceAccount
          type: object
        status:
          description: ComputeNodeOpenStackStatus defines the observed state of ComputeNodeOpenStack
          properties:
            infraDaemonSets:
              description: Infra DaemonSets created
              items:
                description: InfraDaemonSet defines the daemon set required
                properties:
                  name:
                    description: Name
                    type: string
                  namespace:
                    description: Namespace
                    type: string
                required:
                - name
                - namespace
                type: object
              type: array
            nodes:
              description: Nodes information
              items:
                description: Node defines the status of the associated nodes
                properties:
                  name:
                    description: Node name
                    type: string
                  status:
                    description: Node status
                    type: string
                required:
                - name
                - status
                type: object
              type: array
            nodesToDelete:
              description: Nodes to delete upon scale down
              items:
                description: NodeToDelete defines the name of the node to delete and
                  if automatic drain is needed
                properties:
                  drain:
                    description: Automatic draining of the node
                    type: boolean
                  name:
                    description: Node Name
                    type: string
                required:
                - name
                type: object
              type: array
            readyWorkers:
              description: Number of ready workers
              format: int32
              type: integer
            specMDS:
              description: Applied Spec
              type: string
            workers:
              description: 'Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
                Number of requested workers'
              format: int32
              type: integer
          required:
          - specMDS
          - workers
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
